### ISSUE TITLE
Unable to get application to start. TypeError: Cannot destructure property 'locationFullName' of 'input' as it is null.

### ISSUE THREAD

**Issue by christopherbclark** [maxCopell/tripadvisor-scraper#7]
When I run node index in powershell, I get the following error. How/Where do I set "locationFullName" so that the app runs?

INFO  System info {"apifyVersion":"0.20.3","apifyClientVersion":"0.6.0","osType":"Windows_NT","nodeVersion":"v12.16.3"}
WARN  Neither APIFY_LOCAL_STORAGE_DIR nor APIFY_TOKEN environment variable is set, defaulting to APIFY_LOCAL_STORAGE_DIR="C:\Users\chris\documents\Scraper\apify_storage"
ERROR The function passed to Apify.main() threw an exception:
  TypeError: Cannot destructure property 'locationFullName' of 'input' as it is null.
      at validateInput (C:\Users\chris\documents\Scraper\src\tools\general.js:208:9)
      at C:\Users\chris\documents\Scraper\src\main.js:35:5
      at async run (C:\Users\chris\documents\Scraper\node_modules\apify\build\actor.js:238:13)
PS C:\Users\chris\documents\Scraper>

**Comment by christopherbclark** [comment]
I’m an idiot. I didn’t realize we needed to use Apify.
